### PR TITLE
Issue 164 165 fixes

### PR DESCRIPTION
**Pull request by georgenalen**
Overall Review of Changes:
Fixed two issues

Issue Fixes:
#164  - Added single quotes to RHEL version number in pre_remediation_audit.yml
#165  - Added run_audit tag to run post remediation audit

Enhancements:
n/a

How has this been tested?:
Locally
Signed-off-by: George Nalen [georgen@mindpointgroup.com](mailto:georgen@mindpointgroup.com)

### CODE REVIEW

**Comment by xpillons** [comment]
@georgenalen there are missing run_audit tags on the `pre_remediation_audit` and `post_remediation_audit` tasks in main.

**Comment by georgenalen** [comment]
@xpillons Thanks for the heads up, I added that in there

**Review by uk-bolly — APPROVED** [review]
looks good

**Comment by xpillons** [comment]
@georgenalen @uk-bolly there is still a missing run_audit tag on the post_remediation_audit task

**Review by uk-bolly — APPROVED** [review]
looks good with new updates

**Pull request merged**
