### PR TITLE
- Fixed handler name typo

### PR DESCRIPTION
**Pull request by MarcoV-git**
- Added protection for skipped resultset items
- Made when statement layout consistent

**Overall Review of Changes:**
A general description of the changes made that are being requested for merge

**Issue Fixes:**
Please list (using linking) any open issues this PR addresses

**Enhancements:**
Please list any enhancements/features that are not open issue tickets

**How has this been tested?:**
Please give an overview of how these changes were tested. If they were not please use N/A

### CODE REVIEW

**Review by uk-bolly — APPROVED** [review]
Great catch on these items thank you

**Comment by uk-bolly** [comment]
Hi @MarcoV-git 

Great catch on finding these issues and supplying the fix. I have noted that the signed-off-by part is missing from the signing commits that we require.
If you could please add that am happy to accept and merge this request.

Many thanks

uk-bolly

**Comment by MarcoV-git** [comment]
Mark,

My commit has been signed. There's an unsigned commit from you:

commit c82d920a59a0cd84f1631c1351bf54def7a4cd9c (HEAD -> devel, origin/devel, origin/HEAD)
Author: Marco V <marco@osp.nl>
Date:   Fri Jul 21 11:04:00 2023 +0200

    - Fixed handler name typo
    - Added protection for skipped resultset items
    - Made when statement layout consistent
    
    Signed-off-by: Marco V <marco@osp.nl>

commit 36f35d0abc7f7aab0a5394bac10d16af63184e90
Merge: f37b8e2 f11d34f
Author: uk-bolly <mark.bollyuk@gmail.com>
Date:   Tue Jul 18 15:25:38 2023 +0100

    Merge pull request #302 from ansible-lockdown/tidy
    
    Tidy up and linting

**Comment by uk-bolly** [comment]
> @uk-bolly ,
> 
> My commit has been signed. There's an unsigned commit from you:
> 
> commit [c82d920](https://github.com/ansible-lockdown/RHEL8-CIS/commit/c82d920a59a0cd84f1631c1351bf54def7a4cd9c) (HEAD -> devel, origin/devel, origin/HEAD) Author: Marco V [marco@osp.nl](mailto:marco@osp.nl) Date: Fri Jul 21 11:04:00 2023 +0200
> 
> ```
> - Fixed handler name typo
> - Added protection for skipped resultset items
> - Made when statement layout consistent
> 
> Signed-off-by: Marco V <marco@osp.nl>
> ```
> 
> commit [36f35d0](https://github.com/ansible-lockdown/RHEL8-CIS/commit/36f35d0abc7f7aab0a5394bac10d16af63184e90) Merge: [f37b8e2](https://github.com/ansible-lockdown/RHEL8-CIS/commit/f37b8e25a664e275664a48c5e5359cc6144d75a4) [f11d34f](https://github.com/ansible-lockdown/RHEL8-CIS/commit/f11d34fd0aa1258128edd2aca2cb667daefc09c3) Author: uk-bolly [mark.bollyuk@gmail.com](mailto:mark.bollyuk@gmail.com) Date: Tue Jul 18 15:25:38 2023 +0100
> 
> ```
> Merge pull request #302 from ansible-lockdown/tidy
> 
> Tidy up and linting
> ```

hi @MarcoV-git 

Apologies for the confusion, I can see it is signed-off i meant to say gpg signed.
A merge commit is a slightly different commit and wouldn't be signed in the same fashion as i was confirming the mergings of other content changes which are both gpg and signed-off by.
The easiest way i have found with github is if you look at the PR and the commits tabs you will see a "verified" icon when it has been GPG signed.
I have looked for a better way to add that test to the pipeline but as yet have not found it as DCO only does half the job.

I hope that makes sense and thank you once again for your time and continuing to follow up.

kindest regards

uk-bolly

**Comment by MarcoV-git** [comment]
@uk-bolly  Finally fixed the pull

**Comment by uk-bolly** [comment]
Great work thank you

**Comment by bbaassssiiee** [comment]
This PR caused CI failure, see issue #306

**Pull request merged**
