### PR TITLE
Update Alma 8 GPG Key

### PR DESCRIPTION
**Pull request by ajython**
Update AlmaLinux.yml

**Overall Review of Changes:**
Following Alma 8 GPG change, the new GPG key needs updating.

**Issue Fixes:**
Please list (using linking) any open issues this PR addresses

**Enhancements:**
Please list any enhancements/features that are not open issue tickets

**How has this been tested?:**
N/A

### CODE REVIEW

**Review by nickthebeer — APPROVED** [review]
This is correct inline with https://almalinux.org/blog/2023-12-20-almalinux-8-key-update/

**Review by uk-bolly — APPROVED** [review]
Brilliant and explanation link included

**Comment by uk-bolly** [comment]
Hi

Thank you for taking the time to raise this PR, really appreciate the fact the url is also added to show the reasoning behind this.
However while all looks good the value that is searched for in the command works a little different.
We are looking for the keyID reference from the release package. in this case the value would be 2ae81e8aced7258b.
This can be seen in the check command that is run in the tasks (it discovers the release rpm)

```rpm -q --queryformat "%{PACKAGER} %{SIGPGP:pgpsig}\n" almalinux-release-8.10-1.el8.x86_64```

The link that you provided really helped to point us in the correct direction.

If you want to change the value, happy to accept the PR or i am able to bring this into another PR im currently working on.

Many thanks

uk-bolly

**Comment by ajython** [comment]
Hello, 
I've updated the PR with the new KeyID. Feel free to merge it with your PR if this needs more work. 
Thanks

**Comment by uk-bolly** [comment]
> Hello, I've updated the PR with the new KeyID. Feel free to merge it with your PR if this needs more work. Thanks

Brilliant work thank you, always nice to be able to merge someone PR rather than add credits.

Thank you 

uk-bolly

**Review by uk-bolly — APPROVED** [review]

**Pull request merged**
